POST localhost:3000/api/createUser
Content-Type: application/json
Authorization: Basic dGVzdDE6MTIzNDU=

{"login": "test5", "name": "My Name Is"}

###
GET localhost:3000/api/auth
Authorization: Basic dGVzdDE6MTIzNDU=


###
GET localhost:3000/api/getUserPosts?userForView=test1
Authorization: Basic dGVzdDE6MTIzNDU=

###
POST localhost:3000/api/createPost
Authorization: Basic dGVzdDE6MTIzNDU=
Content-Type: application/json

{"message": "test"}

###
POST localhost:3000/api/likePost
Authorization: Basic dGVzdDE6MTIzNDU=
Content-Type: application/json

{"messageId": "f153f6a9-3b70-4316-882b-5119aee48882"}
